### ISSUE TITLE
Nigeria, Sierra Leone, Liberia, DRC and Sudan data missing?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#118]
@evz I think you might be making some changes, but the data for various countries has been dumped it looks like. I've done some updating of the data in the Master Import Sheet if you want to just do a reimport. I've updated the Events so that there are some in Mexico.

**Comment by tonysecurityforcemonitor** [comment]
@evz - I'm going to demo the Monitor app a bit for an internal meeting at 3pm today --- could you look at this and try and resolve before then?

**Comment by evz** [comment]
Yup. Working on it now

**Comment by evz** [comment]
@tonysecurityforcemonitor Things should be working. Let me know if you spot anything weird.

**Comment by tonysecurityforcemonitor** [comment]
@evz thanks - Nigeria, Mexico and Sudan look great!

I'm still seeing issues with DRC, Sierra Leone and Liberia-

**Sierra Leone**
United Nations Mission in Sierra Leone - should be displaying since it has an Area - I moved the time slider to an appropriate date but nothing is displaying - http://ffctn.com/clients/on/sfm/M28/#country/sl!date=2002-03-26&focus=map

**DRC**
United Nations Organization Stabilization Mission in the Democratic Republic of the Congo - should be displaying since it has a Site - but nothing is - http://ffctn.com/clients/on/sfm/M28/#country/cd!date=2016-04-27&focus=map

**Liberia**
United Nations Mission in Liberia - should be displaying since it has an Area - but nothing is - http://ffctn.com/clients/on/sfm/M28/#country/lr!date=2016-04-27&focus=map

If part of the issue is the loading of OSM data I can go through and cut DRC and Sierra Leone from the dataset. It would be good to keep Liberia there has been a lot of involvement there.

**Comment by evz** [comment]
OK. I'll spend some time trying to figure out what's up and let you know if I have to do any surgery before I do it. I'd hate for everything to go missing right before you need it for the demo

**Comment by evz** [comment]
OK, I think I figured this out. It's because I'm filtering where there is a site _and_ an area. I can fix the query to return things with a site _or_ an area.

**Comment by evz** [comment]
@tonysecurityforcemonitor Those three views should have organizations in them now.

**Comment by tonysecurityforcemonitor** [comment]
@evz - this is working perfectly - thanks!
