### ISSUE TITLE
[production server] Persons displaying when not a member of a unit?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#486]
@evz 

In the case of Mexico, apparently the commanders from other units of other countries are mixed with Mexican units even though they are not linked to those units in their individual pages.

Searching for "Luis Crescencio Sandoval González" we got some erros in the superiors and subordinates:
![image](https://user-images.githubusercontent.com/18744855/47451064-caa8ec80-d794-11e8-9eb8-53d5e8dec0bf.png)

![image](https://user-images.githubusercontent.com/18744855/47451071-d0063700-d794-11e8-8a55-a3c5bcd8c704.png)

However if I click on the name of the commanders, they are not linked to this units

For example for Isiaku Dikko:
![image](https://user-images.githubusercontent.com/18744855/47451078-d694ae80-d794-11e8-9834-1456cd0e61f1.png)

**Comment by evz** [comment]
@tonysecurityforcemonitor crap this is something that I fixed more recently. let me see if i can figure out where i did that and apply the patch.

**Comment by evz** [comment]
Just so we both know I'm not crazy: https://back.securityforcemonitor.org/en/person/view/d02f55fa-108a-4456-a869-f27750c0a98f/

**Comment by tonysecurityforcemonitor** [comment]
I never doubted you! ; )

I just double checked and the issue is still live on the production side of the coin

**Comment by evz** [comment]
@tonysecurityforcemonitor @tlongers I'm pretty sure this was resolved on Friday. Can you guys check it out and close this if so

**Comment by tlongers** [comment]
Yeah, this is fixed on production. Closing.
